---
servers:
- url: "http://localhost:8080"
openapi: "3.0.0"
paths:
  /users:
    $ref: "./openapi.yaml#/paths/~1users"
  /users/{id}:
    $ref: "./openapi.yaml#/paths/~1users~1{id}"
info:
  title: "merged spec"
  description: "merged spec"
  version: "1.0.0"
